// Generated by BUCKLESCRIPT VERSION 1.7.4, PLEASE EDIT WITH CARE
'use strict';

var Curry                = require("bs-platform/lib/js/curry.js");
var React                = require("react");
var ReactRe              = require("reason-react/lib/js/src/reactRe.js");
var Pervasives           = require("bs-platform/lib/js/pervasives.js");
var Js_null_undefined    = require("bs-platform/lib/js/js_null_undefined.js");
var ReactTransitionGroup = require("react-transition-group");

function createElement(className, transitionName, transitionEnterTimeout, transitionLeaveTimeout) {
  var partial_arg = {
    className: Js_null_undefined.from_opt(className),
    transitionName: String(transitionName),
    transitionEnterTimeout: transitionEnterTimeout,
    transitionLeaveTimeout: transitionLeaveTimeout
  };
  var partial_arg$1 = ReactTransitionGroup.CSSTransitionGroup;
  return function (param, param$1, param$2, param$3) {
    return ReactRe.wrapPropsShamelessly(partial_arg$1, partial_arg, param, param$1, param$2, param$3);
  };
}

var CSSTransitionGroup = /* module */[/* createElement */createElement];

var componentDidMount = ReactRe.Component[0];

var componentWillUpdate = ReactRe.Component[1];

var componentDidUpdate = ReactRe.Component[2];

var componentWillReceiveProps = ReactRe.Component[3];

var componentWillUnmount = ReactRe.Component[4];

var getInstanceVars = ReactRe.Component[5];

var jsPropsToReasonProps = ReactRe.Component[6];

var getInitialState = ReactRe.Component[7];

var name = "Cat";

function render(param) {
  var props = param[/* props */1];
  var byeSelf = props[/* byeSelf */1];
  var match = props[/* cat */0];
  var catItem = match[/* isHidden */3] !== 0 ? null : React.createElement("li", {
          key: Pervasives.string_of_int(match[/* id */0]),
          className: "cat-item"
        }, React.createElement("img", {
              className: "cat-image",
              src: match[/* image */2]
            }), React.createElement("p", {
              className: "cat-fact"
            }, match[/* fact */1]), React.createElement("a", {
              className: "delete-cat",
              href: "#",
              onClick: function (e) {
                e.preventDefault();
                return Curry._1(byeSelf, /* () */0);
              }
            }, "Bye"));
  return createElement(/* None */0, "cat", 500, 500)(/* :: */[
              catItem,
              /* [] */0
            ], /* None */0, /* None */0, /* () */0);
}

var Cat_008 = /* Stateful */ReactRe.Component[8];

var Cat_009 = /* JsProps */ReactRe.Component[9];

var Cat_010 = /* InstanceVars */ReactRe.Component[10];

var Cat = /* module */[
  /* componentDidMount */componentDidMount,
  /* componentWillUpdate */componentWillUpdate,
  /* componentDidUpdate */componentDidUpdate,
  /* componentWillReceiveProps */componentWillReceiveProps,
  /* componentWillUnmount */componentWillUnmount,
  /* getInstanceVars */getInstanceVars,
  /* jsPropsToReasonProps */jsPropsToReasonProps,
  /* getInitialState */getInitialState,
  Cat_008,
  Cat_009,
  Cat_010,
  /* name */name,
  /* render */render
];

var include = ReactRe.CreateComponent([
      name,
      getInstanceVars,
      getInitialState,
      componentDidMount,
      componentWillReceiveProps,
      componentWillUpdate,
      componentDidUpdate,
      componentWillUnmount,
      jsPropsToReasonProps,
      render
    ]);

var wrapProps = include[1];

function createElement$1(cat, byeSelf) {
  return Curry._1(wrapProps, /* record */[
              /* cat */cat,
              /* byeSelf */byeSelf
            ]);
}

var comp = include[0];

exports.CSSTransitionGroup = CSSTransitionGroup;
exports.Cat                = Cat;
exports.comp               = comp;
exports.wrapProps          = wrapProps;
exports.createElement      = createElement$1;
/* include Not a pure module */
