// Generated by BUCKLESCRIPT VERSION 1.7.4, PLEASE EDIT WITH CARE
'use strict';

var Cat        = require("./cat.js");
var List       = require("bs-platform/lib/js/list.js");
var $$Array    = require("bs-platform/lib/js/array.js");
var Curry      = require("bs-platform/lib/js/curry.js");
var React      = require("react");
var ReactRe    = require("reason-react/lib/js/src/reactRe.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");

var componentDidMount = ReactRe.Component[0];

var componentWillUpdate = ReactRe.Component[1];

var componentDidUpdate = ReactRe.Component[2];

var componentWillReceiveProps = ReactRe.Component[3];

var componentWillUnmount = ReactRe.Component[4];

var getInstanceVars = ReactRe.Component[5];

var jsPropsToReasonProps = ReactRe.Component[6];

var getInitialState = ReactRe.Component[7];

var name = "CatList";

function render(param) {
  var match = param[/* props */1];
  var removeCat = match[/* removeCat */1];
  return React.createElement("ul", {
              className: "cat-list"
            }, $$Array.of_list(List.mapi(function (i, cat) {
                      return Curry._4(Cat.createElement(cat, Curry._1(removeCat, cat)), /* [] */0, /* None */0, /* Some */[Pervasives.string_of_int(i)], /* () */0);
                    }, match[/* cats */0])));
}

var CatList_008 = /* Stateful */ReactRe.Component[8];

var CatList_009 = /* JsProps */ReactRe.Component[9];

var CatList_010 = /* InstanceVars */ReactRe.Component[10];

var CatList = /* module */[
  /* componentDidMount */componentDidMount,
  /* componentWillUpdate */componentWillUpdate,
  /* componentDidUpdate */componentDidUpdate,
  /* componentWillReceiveProps */componentWillReceiveProps,
  /* componentWillUnmount */componentWillUnmount,
  /* getInstanceVars */getInstanceVars,
  /* jsPropsToReasonProps */jsPropsToReasonProps,
  /* getInitialState */getInitialState,
  CatList_008,
  CatList_009,
  CatList_010,
  /* name */name,
  /* render */render
];

var include = ReactRe.CreateComponent([
      name,
      getInstanceVars,
      getInitialState,
      componentDidMount,
      componentWillReceiveProps,
      componentWillUpdate,
      componentDidUpdate,
      componentWillUnmount,
      jsPropsToReasonProps,
      render
    ]);

var wrapProps = include[1];

function createElement(cats, removeCat) {
  return Curry._1(wrapProps, /* record */[
              /* cats */cats,
              /* removeCat */removeCat
            ]);
}

var comp = include[0];

exports.CatList       = CatList;
exports.comp          = comp;
exports.wrapProps     = wrapProps;
exports.createElement = createElement;
/* include Not a pure module */
